name: code-validation-and-tests
on: [push]
jobs:
  code-validation-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: "https://registry.npmjs.org"
      - name: setup project
        run: yarn
      - name: format-and-lint
        run: yarn ci:format-and-lint
      - name: test
        run: yarn ci:test
      - name: build
        run: yarn ci:build
